package com.swaminarayan.shikshapatriApp.constants

import com.swaminarayan.shikshapatriApp.R

data class MaharajGuruji(
    val image: Int,
    val isLeftSideFace: Boolean = false,
    val isRightSideFace: Boolean = false
)

val gurujiList = listOf(
    MaharajGuruji(R.drawable.guruji_1),
    MaharajGuruji(R.drawable.guruji_2),
    MaharajGuruji(R.drawable.guruji_3),
    MaharajGuruji(R.drawable.guruji_4_l),
    MaharajGuruji(R.drawable.guruji_5_l),
    MaharajGuruji(R.drawable.guruji_6_l),
    MaharajGuruji(R.drawable.guruji_7_l),
    MaharajGuruji(R.drawable.guruji_8_l),
)
val gurujiLeftFaceList = listOf(
    MaharajGuruji(R.drawable.guruji_4_l),
    MaharajGuruji(R.drawable.guruji_5_l),
    MaharajGuruji(R.drawable.guruji_6_l),
    MaharajGuruji(R.drawable.guruji_7_l),
    MaharajGuruji(R.drawable.guruji_8_l),
)
val gurujiRightFaceList = listOf(
    MaharajGuruji(R.drawable.guruji_4_r),
    MaharajGuruji(R.drawable.guruji_5_r),
    MaharajGuruji(R.drawable.guruji_6_r),
    MaharajGuruji(R.drawable.guruji_7_r),
    MaharajGuruji(R.drawable.guruji_8_r),
)

val maharajList = listOf(

    // Maharaj with Front face.
    MaharajGuruji(R.drawable.maharaj_1),
    MaharajGuruji(R.drawable.maharaj_2),
    MaharajGuruji(R.drawable.maharaj_3),
    MaharajGuruji(R.drawable.maharaj_4),
    MaharajGuruji(R.drawable.maharaj_5),
    MaharajGuruji(R.drawable.maharaj_7),
    MaharajGuruji(R.drawable.maharaj_8),
    MaharajGuruji(R.drawable.maharaj_9),
    MaharajGuruji(R.drawable.maharaj_10),
    MaharajGuruji(R.drawable.maharaj_11),
    MaharajGuruji(R.drawable.maharaj_13),
    MaharajGuruji(R.drawable.maharaj_14),
    MaharajGuruji(R.drawable.maharaj_15),
    MaharajGuruji(R.drawable.maharaj_16),
    MaharajGuruji(R.drawable.maharaj_18),
    MaharajGuruji(R.drawable.maharaj_22),
    MaharajGuruji(R.drawable.maharaj_23),
    MaharajGuruji(R.drawable.maharaj_24),
    MaharajGuruji(R.drawable.maharaj_25),
    MaharajGuruji(R.drawable.maharaj_28),
    MaharajGuruji(R.drawable.maharaj_30),
    MaharajGuruji(R.drawable.maharaj_31),
    MaharajGuruji(R.drawable.maharaj_33),
    MaharajGuruji(R.drawable.maharaj_34),
    MaharajGuruji(R.drawable.maharaj_35),
    MaharajGuruji(R.drawable.maharaj_36),
    MaharajGuruji(R.drawable.maharaj_38),
    MaharajGuruji(R.drawable.maharaj_39),
    MaharajGuruji(R.drawable.maharaj_40),
    MaharajGuruji(R.drawable.maharaj_43),
    MaharajGuruji(R.drawable.maharaj_44),
    MaharajGuruji(R.drawable.maharaj_45),
    MaharajGuruji(R.drawable.maharaj_46),
    MaharajGuruji(R.drawable.maharaj_47),
    MaharajGuruji(R.drawable.maharaj_48),
    MaharajGuruji(R.drawable.maharaj_49),
    MaharajGuruji(R.drawable.maharaj_50),
    MaharajGuruji(R.drawable.maharaj_51),
    MaharajGuruji(R.drawable.maharaj_53),
    MaharajGuruji(R.drawable.maharaj_54),
    MaharajGuruji(R.drawable.maharaj_56),
    MaharajGuruji(R.drawable.maharaj_57),
    MaharajGuruji(R.drawable.maharaj_59),
    MaharajGuruji(R.drawable.maharaj_60),
    MaharajGuruji(R.drawable.maharaj_61),
    MaharajGuruji(R.drawable.maharaj_63),
    MaharajGuruji(R.drawable.maharaj_65),
    MaharajGuruji(R.drawable.maharaj_66),
    MaharajGuruji(R.drawable.maharaj_67),
    MaharajGuruji(R.drawable.maharaj_68),
    MaharajGuruji(R.drawable.maharaj_70),
    MaharajGuruji(R.drawable.maharaj_71),
    MaharajGuruji(R.drawable.maharaj_72),
    MaharajGuruji(R.drawable.maharaj_73),
    MaharajGuruji(R.drawable.maharaj_74),
    MaharajGuruji(R.drawable.maharaj_76),
    MaharajGuruji(R.drawable.maharaj_77),
    MaharajGuruji(R.drawable.maharaj_78),
    MaharajGuruji(R.drawable.maharaj_79),
    MaharajGuruji(R.drawable.maharaj_80),
    MaharajGuruji(R.drawable.maharaj_81),
    MaharajGuruji(R.drawable.maharaj_83),
    MaharajGuruji(R.drawable.maharaj_84),
    MaharajGuruji(R.drawable.maharaj_86),
    MaharajGuruji(R.drawable.maharaj_87),
    MaharajGuruji(R.drawable.maharaj_88),
    MaharajGuruji(R.drawable.maharaj_89),
    MaharajGuruji(R.drawable.maharaj_90),
    MaharajGuruji(R.drawable.maharaj_91),
    MaharajGuruji(R.drawable.maharaj_92),
    MaharajGuruji(R.drawable.maharaj_93),
    MaharajGuruji(R.drawable.maharaj_94),
    MaharajGuruji(R.drawable.maharaj_95),
    MaharajGuruji(R.drawable.maharaj_96),
    MaharajGuruji(R.drawable.maharaj_98),
    MaharajGuruji(R.drawable.maharaj_99),
    MaharajGuruji(R.drawable.maharaj_100),
    MaharajGuruji(R.drawable.maharaj_101),
    MaharajGuruji(R.drawable.maharaj_102),
    MaharajGuruji(R.drawable.maharaj_103),
    MaharajGuruji(R.drawable.maharaj_104),
    MaharajGuruji(R.drawable.maharaj_105),
    MaharajGuruji(R.drawable.maharaj_106),
    MaharajGuruji(R.drawable.maharaj_107),
    MaharajGuruji(R.drawable.maharaj_108),
    MaharajGuruji(R.drawable.maharaj_109),
    MaharajGuruji(R.drawable.maharaj_110),
    MaharajGuruji(R.drawable.maharaj_111),
    MaharajGuruji(R.drawable.maharaj_112),
    MaharajGuruji(R.drawable.maharaj_113),
    MaharajGuruji(R.drawable.maharaj_114),
    MaharajGuruji(R.drawable.maharaj_115),
    MaharajGuruji(R.drawable.maharaj_116),
    MaharajGuruji(R.drawable.maharaj_117),
    MaharajGuruji(R.drawable.maharaj_118),
    MaharajGuruji(R.drawable.maharaj_119),
    MaharajGuruji(R.drawable.maharaj_120),
    MaharajGuruji(R.drawable.maharaj_122),
    MaharajGuruji(R.drawable.maharaj_124),
    MaharajGuruji(R.drawable.maharaj_125),
    MaharajGuruji(R.drawable.maharaj_126),
    MaharajGuruji(R.drawable.maharaj_127),
    MaharajGuruji(R.drawable.maharaj_129),
    MaharajGuruji(R.drawable.maharaj_130),
    MaharajGuruji(R.drawable.maharaj_131),
    MaharajGuruji(R.drawable.maharaj_133),
    MaharajGuruji(R.drawable.maharaj_134),
    MaharajGuruji(R.drawable.maharaj_135),
    MaharajGuruji(R.drawable.maharaj_136),
    MaharajGuruji(R.drawable.maharaj_137),
    MaharajGuruji(R.drawable.maharaj_138),
    MaharajGuruji(R.drawable.maharaj_139),
    MaharajGuruji(R.drawable.maharaj_140),
    MaharajGuruji(R.drawable.maharaj_141),
    MaharajGuruji(R.drawable.maharaj_143),
    MaharajGuruji(R.drawable.maharaj_145),
    MaharajGuruji(R.drawable.maharaj_147),
    MaharajGuruji(R.drawable.maharaj_148),
    MaharajGuruji(R.drawable.maharaj_149),
    MaharajGuruji(R.drawable.maharaj_150),
    MaharajGuruji(R.drawable.maharaj_152),
    MaharajGuruji(R.drawable.maharaj_153),
    MaharajGuruji(R.drawable.maharaj_154),
    MaharajGuruji(R.drawable.maharaj_155),
    MaharajGuruji(R.drawable.maharaj_156),
    MaharajGuruji(R.drawable.maharaj_157),
    MaharajGuruji(R.drawable.maharaj_158),
    MaharajGuruji(R.drawable.maharaj_159),
    MaharajGuruji(R.drawable.maharaj_160),
    MaharajGuruji(R.drawable.maharaj_161),
    MaharajGuruji(R.drawable.maharaj_162),
    MaharajGuruji(R.drawable.maharaj_163),
    MaharajGuruji(R.drawable.maharaj_165),
    MaharajGuruji(R.drawable.maharaj_166),
    MaharajGuruji(R.drawable.maharaj_167),
    MaharajGuruji(R.drawable.maharaj_168),
    MaharajGuruji(R.drawable.maharaj_169),
    MaharajGuruji(R.drawable.maharaj_170),
    MaharajGuruji(R.drawable.maharaj_171),
    MaharajGuruji(R.drawable.maharaj_172),
    MaharajGuruji(R.drawable.maharaj_173),
    MaharajGuruji(R.drawable.maharaj_174),

    // Maharaj with Left side face.
    MaharajGuruji(R.drawable.maharaj_6, isLeftSideFace = true, isRightSideFace = false),
    MaharajGuruji(R.drawable.maharaj_17, isLeftSideFace = true, isRightSideFace = false),
    MaharajGuruji(R.drawable.maharaj_21, isLeftSideFace = true, isRightSideFace = false),
    MaharajGuruji(R.drawable.maharaj_26, isLeftSideFace = true, isRightSideFace = false),
    MaharajGuruji(R.drawable.maharaj_29, isLeftSideFace = true, isRightSideFace = false),
    MaharajGuruji(R.drawable.maharaj_41, isLeftSideFace = true, isRightSideFace = false),
    MaharajGuruji(R.drawable.maharaj_42, isLeftSideFace = true, isRightSideFace = false),
    MaharajGuruji(R.drawable.maharaj_52, isLeftSideFace = true, isRightSideFace = false),
    MaharajGuruji(R.drawable.maharaj_58, isLeftSideFace = true, isRightSideFace = false),
    MaharajGuruji(R.drawable.maharaj_64, isLeftSideFace = true, isRightSideFace = false),
    MaharajGuruji(R.drawable.maharaj_75, isLeftSideFace = true, isRightSideFace = false),
    MaharajGuruji(R.drawable.maharaj_82, isLeftSideFace = true, isRightSideFace = false),
    MaharajGuruji(R.drawable.maharaj_121, isLeftSideFace = true, isRightSideFace = false),
    MaharajGuruji(R.drawable.maharaj_123, isLeftSideFace = true, isRightSideFace = false),
    MaharajGuruji(R.drawable.maharaj_128, isLeftSideFace = true, isRightSideFace = false),
    MaharajGuruji(R.drawable.maharaj_142, isLeftSideFace = true, isRightSideFace = false),
    MaharajGuruji(R.drawable.maharaj_144, isLeftSideFace = true, isRightSideFace = false),
    MaharajGuruji(R.drawable.maharaj_164, isLeftSideFace = true, isRightSideFace = false),
    MaharajGuruji(R.drawable.maharaj_175, isLeftSideFace = true, isRightSideFace = false),

    // Maharaj with Right side face.
    MaharajGuruji(R.drawable.maharaj_12, isLeftSideFace = false, isRightSideFace = true),
    MaharajGuruji(R.drawable.maharaj_19, isLeftSideFace = false, isRightSideFace = true),
    MaharajGuruji(R.drawable.maharaj_20, isLeftSideFace = false, isRightSideFace = true),
    MaharajGuruji(R.drawable.maharaj_27, isLeftSideFace = false, isRightSideFace = true),
    MaharajGuruji(R.drawable.maharaj_32, isLeftSideFace = false, isRightSideFace = true),
    MaharajGuruji(R.drawable.maharaj_37, isLeftSideFace = false, isRightSideFace = true),
    MaharajGuruji(R.drawable.maharaj_55, isLeftSideFace = false, isRightSideFace = true),
    MaharajGuruji(R.drawable.maharaj_62, isLeftSideFace = false, isRightSideFace = true),
    MaharajGuruji(R.drawable.maharaj_69, isLeftSideFace = false, isRightSideFace = true),
    MaharajGuruji(R.drawable.maharaj_85, isLeftSideFace = false, isRightSideFace = true),
    MaharajGuruji(R.drawable.maharaj_97, isLeftSideFace = false, isRightSideFace = true),
    MaharajGuruji(R.drawable.maharaj_132, isLeftSideFace = false, isRightSideFace = true),
    MaharajGuruji(R.drawable.maharaj_146, isLeftSideFace = false, isRightSideFace = true),
    MaharajGuruji(R.drawable.maharaj_151, isLeftSideFace = false, isRightSideFace = true),
)