package com.swaminarayan.shikshapatriApp.constants

import com.swaminarayan.shikshapatriApp.R

data class MaharajGuruji(
    val image: Int,
    val isLeftSideFace: Boolean
)

val gurujiList = listOf(
    MaharajGuruji(R.drawable.guruji_1, false),
    MaharajGuruji(R.drawable.guruji_2, false),
    MaharajGuruji(R.drawable.guruji_6, false),
    MaharajGuruji(R.drawable.guruji_3, true),
    MaharajGuruji(R.drawable.guruji_4, true),
    MaharajGuruji(R.drawable.guruji_5, true)
)
val gurujiFrontFaceList = listOf(
    MaharajGuruji(R.drawable.guruji_1, false),
    MaharajGuruji(R.drawable.guruji_2, false),
    MaharajGuruji(R.drawable.guruji_6, false)
)

val maharajList = listOf(
    MaharajGuruji(R.drawable.maharaj_1, false),
    MaharajGuruji(R.drawable.maharaj_2, false),
    MaharajGuruji(R.drawable.maharaj_3, false),
    MaharajGuruji(R.drawable.maharaj_4, false),
    MaharajGuruji(R.drawable.maharaj_5, false),
    MaharajGuruji(R.drawable.maharaj_6, true),
    MaharajGuruji(R.drawable.maharaj_7, false),
    MaharajGuruji(R.drawable.maharaj_8, false),
    MaharajGuruji(R.drawable.maharaj_9, false),
    MaharajGuruji(R.drawable.maharaj_10, false),
    MaharajGuruji(R.drawable.maharaj_11, false),
    MaharajGuruji(R.drawable.maharaj_12, false),
    MaharajGuruji(R.drawable.maharaj_13, false),
    MaharajGuruji(R.drawable.maharaj_14, false),
    MaharajGuruji(R.drawable.maharaj_15, false),
    MaharajGuruji(R.drawable.maharaj_16, false),
    MaharajGuruji(R.drawable.maharaj_17, true),
    MaharajGuruji(R.drawable.maharaj_18, false),
    MaharajGuruji(R.drawable.maharaj_19, false),
    MaharajGuruji(R.drawable.maharaj_20, false),
    MaharajGuruji(R.drawable.maharaj_21, true),
    MaharajGuruji(R.drawable.maharaj_22, false),
    MaharajGuruji(R.drawable.maharaj_23, false),
    MaharajGuruji(R.drawable.maharaj_24, false),
    MaharajGuruji(R.drawable.maharaj_25, false),
    MaharajGuruji(R.drawable.maharaj_26, true),
    MaharajGuruji(R.drawable.maharaj_27, false),
    MaharajGuruji(R.drawable.maharaj_28, false),
    MaharajGuruji(R.drawable.maharaj_29, true),
    MaharajGuruji(R.drawable.maharaj_30, false),
    MaharajGuruji(R.drawable.maharaj_31, false),
    MaharajGuruji(R.drawable.maharaj_32, false),
    MaharajGuruji(R.drawable.maharaj_33, false),
    MaharajGuruji(R.drawable.maharaj_34, false),
    MaharajGuruji(R.drawable.maharaj_35, false),
    MaharajGuruji(R.drawable.maharaj_36, false),
    MaharajGuruji(R.drawable.maharaj_37, false),
    MaharajGuruji(R.drawable.maharaj_38, false),
    MaharajGuruji(R.drawable.maharaj_39, false),
    MaharajGuruji(R.drawable.maharaj_40, false),
    MaharajGuruji(R.drawable.maharaj_41, true),
    MaharajGuruji(R.drawable.maharaj_42, true),
    MaharajGuruji(R.drawable.maharaj_43, false),
    MaharajGuruji(R.drawable.maharaj_44, false),
    MaharajGuruji(R.drawable.maharaj_45, false),
    MaharajGuruji(R.drawable.maharaj_46, false),
    MaharajGuruji(R.drawable.maharaj_47, false),
    MaharajGuruji(R.drawable.maharaj_48, false),
    MaharajGuruji(R.drawable.maharaj_49, false),
    MaharajGuruji(R.drawable.maharaj_50, false),
    MaharajGuruji(R.drawable.maharaj_51, false),
    MaharajGuruji(R.drawable.maharaj_52, true),
    MaharajGuruji(R.drawable.maharaj_53, false),
    MaharajGuruji(R.drawable.maharaj_54, false),
    MaharajGuruji(R.drawable.maharaj_55, false),
    MaharajGuruji(R.drawable.maharaj_56, false),
    MaharajGuruji(R.drawable.maharaj_57, false),
    MaharajGuruji(R.drawable.maharaj_58, false),
    MaharajGuruji(R.drawable.maharaj_59, false),
    MaharajGuruji(R.drawable.maharaj_60, false),
    MaharajGuruji(R.drawable.maharaj_61, false),
    MaharajGuruji(R.drawable.maharaj_62, false),
    MaharajGuruji(R.drawable.maharaj_63, false),
    MaharajGuruji(R.drawable.maharaj_64, true),
    MaharajGuruji(R.drawable.maharaj_65, false),
    MaharajGuruji(R.drawable.maharaj_66, false),
    MaharajGuruji(R.drawable.maharaj_67, false),
    MaharajGuruji(R.drawable.maharaj_68, false),
    MaharajGuruji(R.drawable.maharaj_69, false),
    MaharajGuruji(R.drawable.maharaj_70, false),
    MaharajGuruji(R.drawable.maharaj_71, false),
    MaharajGuruji(R.drawable.maharaj_72, false),
    MaharajGuruji(R.drawable.maharaj_73, false),
    MaharajGuruji(R.drawable.maharaj_74, false),
    MaharajGuruji(R.drawable.maharaj_75, false),
    MaharajGuruji(R.drawable.maharaj_76, false),
    MaharajGuruji(R.drawable.maharaj_77, false),
    MaharajGuruji(R.drawable.maharaj_78, false),
    MaharajGuruji(R.drawable.maharaj_79, false),
    MaharajGuruji(R.drawable.maharaj_80, false),
    MaharajGuruji(R.drawable.maharaj_81, false),
    MaharajGuruji(R.drawable.maharaj_82, true),
    MaharajGuruji(R.drawable.maharaj_83, false),
    MaharajGuruji(R.drawable.maharaj_84, false),
    MaharajGuruji(R.drawable.maharaj_85, false),
    MaharajGuruji(R.drawable.maharaj_86, false),
    MaharajGuruji(R.drawable.maharaj_87, false),
    MaharajGuruji(R.drawable.maharaj_88, false),
    MaharajGuruji(R.drawable.maharaj_89, false),
    MaharajGuruji(R.drawable.maharaj_90, false),
    MaharajGuruji(R.drawable.maharaj_91, false),
    MaharajGuruji(R.drawable.maharaj_92, false),
    MaharajGuruji(R.drawable.maharaj_93, false),
    MaharajGuruji(R.drawable.maharaj_94, false),
    MaharajGuruji(R.drawable.maharaj_95, false),
    MaharajGuruji(R.drawable.maharaj_96, false),
    MaharajGuruji(R.drawable.maharaj_97, false),
    MaharajGuruji(R.drawable.maharaj_98, false),
    MaharajGuruji(R.drawable.maharaj_99, false),
    MaharajGuruji(R.drawable.maharaj_100, false),
    MaharajGuruji(R.drawable.maharaj_101, false),
    MaharajGuruji(R.drawable.maharaj_102, false),
    MaharajGuruji(R.drawable.maharaj_103, false),
    MaharajGuruji(R.drawable.maharaj_104, false),
    MaharajGuruji(R.drawable.maharaj_105, false),
    MaharajGuruji(R.drawable.maharaj_106, false),
    MaharajGuruji(R.drawable.maharaj_107, false),
    MaharajGuruji(R.drawable.maharaj_108, false),
    MaharajGuruji(R.drawable.maharaj_109, false),
    MaharajGuruji(R.drawable.maharaj_110, false),
    MaharajGuruji(R.drawable.maharaj_111, false),
    MaharajGuruji(R.drawable.maharaj_112, false),
    MaharajGuruji(R.drawable.maharaj_113, false),
    MaharajGuruji(R.drawable.maharaj_114, false),
    MaharajGuruji(R.drawable.maharaj_115, false),
    MaharajGuruji(R.drawable.maharaj_116, false),
    MaharajGuruji(R.drawable.maharaj_117, false),
    MaharajGuruji(R.drawable.maharaj_118, false),
    MaharajGuruji(R.drawable.maharaj_119, false),
    MaharajGuruji(R.drawable.maharaj_120, false),
    MaharajGuruji(R.drawable.maharaj_121, true),
    MaharajGuruji(R.drawable.maharaj_122, false),
    MaharajGuruji(R.drawable.maharaj_123, true),
    MaharajGuruji(R.drawable.maharaj_124, false),
    MaharajGuruji(R.drawable.maharaj_125, false),
    MaharajGuruji(R.drawable.maharaj_126, false),
    MaharajGuruji(R.drawable.maharaj_127, false),
    MaharajGuruji(R.drawable.maharaj_128, true),
    MaharajGuruji(R.drawable.maharaj_129, false),
    MaharajGuruji(R.drawable.maharaj_130, false),
    MaharajGuruji(R.drawable.maharaj_131, false),
    MaharajGuruji(R.drawable.maharaj_132, false),
    MaharajGuruji(R.drawable.maharaj_133, false),
    MaharajGuruji(R.drawable.maharaj_134, false),
    MaharajGuruji(R.drawable.maharaj_135, false),
    MaharajGuruji(R.drawable.maharaj_136, false),
    MaharajGuruji(R.drawable.maharaj_137, false),
    MaharajGuruji(R.drawable.maharaj_138, false),
    MaharajGuruji(R.drawable.maharaj_139, false),
    MaharajGuruji(R.drawable.maharaj_140, false),
    MaharajGuruji(R.drawable.maharaj_141, false),
    MaharajGuruji(R.drawable.maharaj_142, false),
    MaharajGuruji(R.drawable.maharaj_143, false),
    MaharajGuruji(R.drawable.maharaj_144, true),
    MaharajGuruji(R.drawable.maharaj_145, false),
    MaharajGuruji(R.drawable.maharaj_146, false),
    MaharajGuruji(R.drawable.maharaj_147, false),
    MaharajGuruji(R.drawable.maharaj_148, false),
    MaharajGuruji(R.drawable.maharaj_149, false),
    MaharajGuruji(R.drawable.maharaj_150, false),
    MaharajGuruji(R.drawable.maharaj_151, false),
    MaharajGuruji(R.drawable.maharaj_152, false),
    MaharajGuruji(R.drawable.maharaj_153, false),
    MaharajGuruji(R.drawable.maharaj_154, false),
    MaharajGuruji(R.drawable.maharaj_155, false),
    MaharajGuruji(R.drawable.maharaj_156, false),
    MaharajGuruji(R.drawable.maharaj_157, false),
    MaharajGuruji(R.drawable.maharaj_158, false),
    MaharajGuruji(R.drawable.maharaj_159, false),
    MaharajGuruji(R.drawable.maharaj_160, false),
    MaharajGuruji(R.drawable.maharaj_161, false),
)


















